# Generated by Django 6.0.1 on 2026-02-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube, Vimeo, or other video URL', max_length=500, null=True),
        ),
    ]
