# Generated by Django 6.0.1 on 2026-02-06 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_lesson_video_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ('id',)},
        ),
    ]
