# Generated by Django 6.0.1 on 2026-02-10 06:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("acounts", "0002_user_enrolled_courses_branch_user_branch"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentprofile",
            name="attendance_percentage",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="current_gpa",
        ),
    ]
