# Generated by Django 6.0.1 on 2026-02-11 04:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acounts", "0003_remove_studentprofile_attendance_percentage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="admission_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="father_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="grade_level",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="guardian_phone",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="mother_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
