# Generated by Django 6.0.1 on 2026-02-11 04:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acounts", "0004_alter_studentprofile_admission_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacherprofile",
            name="department",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="teacherprofile",
            name="hire_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="teacherprofile",
            name="qualification",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="teacherprofile",
            name="subject_specialization",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
