# Generated by Django 6.0.1 on 2026-02-11 04:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acounts", "0005_alter_teacherprofile_department_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="must_change_password",
            field=models.BooleanField(
                default=True, help_text="User must change password on first login"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="otp_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="otp_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="password_reset_otp",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
